name: Build and Deploy code on Stage Server
on:
  push:
    branches: [ "stage" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        if: github.ref == 'refs/heads/main'
        run: |
          pwd
      - name: Deploy to AWS EC2 develop
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Hi sathyan"
