name: CI
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: COPY stage PEM key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy to Server
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          ssh -o StrictHostKeyChecking=no  -i ~/.ssh/aws.pem alyf_user@13.91.220.141 ' $REPO_NAME"'
