name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone alyf_pyutils and checkout pull request branch
        run: |
          REPO_NAME="alyf_pyutils"
          PR=$(echo ${{github.event.pull_request.number }})
          echo $PR
          git clone "https://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@github.com/alyf-lab/alyf_pyutils.git"
          cd $REPO_NAME
          git fetch origin pull/122/head:pr-122
          git checkout pr-122
          cat README.md
          cd ..

      - name: Clone alyf_api_server
        run: git clone "https://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@github.com/alyf-lab/alyf_api_server.git"

      - name: Copy content from alyf_pyutils to alyf_api_server
        run: cp -r $REPO_NAME alyf_api_server/

      - name: Update requirements in alyf_api_server
        run: sed -i 's|git+https://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@github.com/alyf-lab/alyf_pyutils.git|#git+https://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@github.com/alyf-lab/alyf_pyutils.git\n/app/alyf_pyutils/|' alyf_api_server/requirements/prod.txt

      - name: Display updated requirements
        run: cat alyf_api_server/requirements/prod.txt

      - name: Source .env
        run: source alyf_api_server/.env

      - name: Set environment variable
        run: echo "ALYF_USER=sdesai" >> $GITHUB_ENV

      - name: Execute deployment script
        run: alyf_api_server/new_deploy.sh
